version: '3.9'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/build:/srv  # Path to the static build of your SvelteKit site
      - caddy_data:/data
      - caddy_config:/config
    hostname: caddy.local

  fastapi:
    container_name: backend
    restart: always
    networks:
      - app_network
    build:
      context: ./backend  # Path to your FastAPI app
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    hostname: backend.local

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env.production
    hostname: postgres.local

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
