version: '3.9'

services:
  caddy:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: caddy
    restart: always
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    hostname: caddy.local
    depends_on:
      - fastapi

  fastapi:
    container_name: backend
    restart: always
    networks:
      - app_network
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    hostname: backend.local
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env.production
    hostname: postgres.local

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
